project:
  type: website
  output-dir: docs
  resources:
    - .nojekyll
    - Documentation/Progress/
    - Documentation/Functions_test_coverage/
    - Documentation/Presentations/IAVS_2026/_output/
  render:
    - "index.qmd"
    - "Documentation/Website/**/*.qmd"

website:
  title: "BIODYNAMICS-vegetation-cooccurrence"
  page-footer:
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
  site-url: https://ondrejmottl.github.io/BIODYNAMICS-vegetation-cooccurrence/
  repo-url: https://github.com/OndrejMottl/BIODYNAMICS-vegetation-cooccurrence
  issue-url: https://github.com/OndrejMottl/BIODYNAMICS-vegetation-cooccurrence/issues
  repo-actions: [source, issue]

  image: figures/Logo%20FOSSILPOL%20regular%20-%20600ppi.png
  favicon: figures/Logo%20FOSSILPOL%20regular%20-%20600ppi.png
  back-to-top-navigation: true

  sidebar:
    pinned: true
    align: center
    style: "docked"
    collapse-level: 1
    contents:
      - text: "Home"
        href: index.qmd

      - text: "Methods"
        href: Documentation/Website/about.qmd

      - text: "Reproducibility"
        href: Documentation/Website/installation.qmd

      - text: "Outputs"
        href: Documentation/Website/outputs.qmd

      - section: "Code Reference"
        contents:
          - text: "Overview"
            href: Documentation/Website/Documentation/documentation.qmd
          - section: "Functions"
            contents: "Documentation/Website/Documentation/Functions/*.qmd"

format:
  html:
    theme:
      - darkly
      - styles.scss
    toc: true
    toc-location: right
    toc-depth: 2
