default:
  target_store: default
  seed: 1234
  data_processing:
    time_step: 500
    number_of_taxa: !expr Inf
    minimal_proportion_of_pollen: 0.01
    min_n_cores: 2
    min_n_samples: 1
  model_fitting:
    n_cores: 5
    n_mev: 2
    samples: 100
    error_family: "binomial"
    spatial_crs: 3035
    spatial_mode: "spatial"
    use_spatial: true
    use_age_in_formula: true
project_cz:
  target_store: Data/targets/project_cz
  vegvault_data:
    x_lim: !expr c(12, 18.9)
    y_lim: !expr c(48.5, 51.5)
    age_lim: !expr c(0, 5000)
    sel_dataset_type: !expr c("fossil_pollen_archive", "gridpoints")
    sel_abiotic_var_name: !expr c("bio1", "bio12")
  data_processing:
    taxonomic_resolution: "genus"
    min_n_samples: 5
  model_fitting:
    n_mev: 5
    n_cores: 24
    samples: 1000
    spatial_mode: "spatiotemporal"
project_temporal_europe:
  target_store: Data/targets/project_temporal_europe
  vegvault_data:
    x_lim: !expr c(-10, 40)
    y_lim: !expr c(35, 70)
    age_lim: !expr c(0, 20e3)
    sel_dataset_type: !expr c("fossil_pollen_archive","gridpoints")
    sel_abiotic_var_name: !expr c("bio1", "bio4", "bio6", "bio12", "bio15", "bio18", "bio19")
  data_processing:
    taxonomic_resolution: "genus"
    min_n_samples: 10
  model_fitting:
    n_cores: 12
    samples: 2500
project_spatial_continental:
  target_store: Data/targets/spatial_continental
  vegvault_data:
    age_lim: !expr c(0, 20e3)
    sel_dataset_type: !expr c("fossil_pollen_archive", "gridpoints")
    sel_abiotic_var_name: !expr c("bio1", "bio4", "bio6", "bio12", "bio15", "bio18", "bio19")
  data_processing:
    taxonomic_resolution: "genus"
    min_n_samples: 10
  model_fitting:
    n_cores: 12
    samples: 2500
project_spatial_regional:
  target_store: Data/targets/spatial_regional
  vegvault_data:
    age_lim: !expr c(0, 20e3)
    sel_dataset_type: !expr c("fossil_pollen_archive", "gridpoints")
    sel_abiotic_var_name: !expr c("bio1", "bio4", "bio6", "bio12", "bio15", "bio18", "bio19")
  data_processing:
    taxonomic_resolution: "genus"
    min_n_samples: 10
  model_fitting:
    n_cores: 12
    samples: 1000
project_spatial_local:
  target_store: Data/targets/spatial_local
  vegvault_data:
    age_lim: !expr c(0, 20e3)
    sel_dataset_type: !expr c("fossil_pollen_archive", "gridpoints")
    sel_abiotic_var_name: !expr c("bio1", "bio4", "bio6", "bio12", "bio15", "bio18", "bio19")
  data_processing:
    taxonomic_resolution: "genus"
    min_n_samples: 5
  model_fitting:
    n_cores: 12
    samples: 500
