default:
  target_store: default
  seed: 1234
  graphical:
    text_size: 10
    line_size: 0.1
    image_width: 16
    image_height: 12
    image_units: "cm"
project_cz:
  target_store: Data/targets/project_cz
  vegvault_data:
    x_lim: !expr c(12, 18.9)
    y_lim: !expr c(48.5, 51.5)
    age_lim: !expr c(0, 5000)
    sel_dataset_type: !expr c("fossil_pollen_archive", "gridpoints")
    sel_abiotic_var_name: !expr c("bio1", "bio12")
  data_processing:
    time_step: 500
    min_distance_of_gpp_knots: 50
    number_of_taxa: 10
project_europe:
  target_store: Data/targets/project_europe
  vegvault_data:
    x_lim: !expr c(-10, 40)
    y_lim: !expr c(35, 70)
    age_lim: !expr c(0, 20e3)
    sel_dataset_type: !expr c("fossil_pollen_archive","gridpoints")
    sel_abiotic_var_name: !expr c("bio1", "bio4", "bio6", "bio12", "bio15", "bio18", "bio19")
  data_processing:
    time_step: 500
    min_distance_of_gpp_knots: 100
    number_of_taxa: Inf
