---
format: html
title: get_community_data()
---

<html><head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes" />
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.15.3/dist/katex.min.css">
<script type="text/javascript">
const macros = { "\\R": "\\textsf{R}", "\\code": "\\texttt"};
function processMathHTML() {
    var l = document.getElementsByClassName('reqn');
    for (let e of l) { katex.render(e.textContent, e, { throwOnError: false, macros }); }
    return;
}</script>
<script defer src="https://cdn.jsdelivr.net/npm/katex@0.15.3/dist/katex.min.js"
    onload="processMathHTML();"></script>
<link rel="stylesheet" type="text/css" href="R.css" />
</head><body><div class="container"><main>

<table style="width: 100%;"><tr><td>get_community_data</td><td style="text-align: right;">R Documentation</td></tr></table>

<h2>Get Community Data</h2>

<h3>Description</h3>

<p>This function processes a data frame containing community data
and extracts the relevant columns, unnesting the 'data_community'
column in the process.
</p>


<h3>Usage</h3>

<pre><code class='language-R'>get_community_data(data = NULL)
</code></pre>


<h3>Arguments</h3>

<table>
<tr><td><code id="data">data</code></td>
<td>
<p>A data frame. Must contain the columns 'dataset_name' and
'data_community'.</p>
</td></tr>
</table>


<h3>Details</h3>

<p>The function performs the following steps:
</p>

<ul>
<li><p> Validates that the input is a data frame.
</p>
</li>
<li><p> Ensures the presence of the 'dataset_name' and 'data_community' columns.
</p>
</li>
<li><p> Selects the 'dataset_name' and 'data_community' columns.
</p>
</li>
<li><p> Unnests the 'data_community' column.
</p>
</li></ul>



<h3>Value</h3>

<p>A data frame with the 'dataset_name' and unnested 'data_community' columns.
</p>

</main>

</div>
</body></html>

