---
format: html
---

<html><head><title>R: Select N Taxa</title>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes" />
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.15.3/dist/katex.min.css">
<script type="text/javascript">
const macros = { "\\R": "\\textsf{R}", "\\code": "\\texttt"};
function processMathHTML() {
    var l = document.getElementsByClassName('reqn');
    for (let e of l) { katex.render(e.textContent, e, { throwOnError: false, macros }); }
    return;
}</script>
<script defer src="https://cdn.jsdelivr.net/npm/katex@0.15.3/dist/katex.min.js"
    onload="processMathHTML();"></script>
<link rel="stylesheet" type="text/css" href="R.css" />
</head><body><div class="container"><main>

<table style="width: 100%;"><tr><td>select_n_taxa</td><td style="text-align: right;">R Documentation</td></tr></table>

<h2>Select N Taxa</h2>

<h3>Description</h3>

<p>Selects the top N taxa based on their occurrence across datasets.
</p>


<h3>Usage</h3>

<pre><code class='language-R'>select_n_taxa(data = NULL, n_taxa = Inf, per = "dataset_name")
</code></pre>


<h3>Arguments</h3>

<table>
<tr><td><code id="data">data</code></td>
<td>
<p>A data frame containing the input data. Must include columns &quot;taxon&quot; and
the column specified in the 'per' parameter.</p>
</td></tr>
<tr><td><code id="n_taxa">n_taxa</code></td>
<td>
<p>A numeric value specifying the number of taxa to select. Default is Inf.</p>
</td></tr>
<tr><td><code id="per">per</code></td>
<td>
<p>A character string specifying the column name to group by. Default is
&quot;dataset_name&quot;.</p>
</td></tr>
</table>


<h3>Details</h3>

<p>The function identifies the most common taxa across datasets by counting
their occurrences. It then filters the input data to include only the
selected taxa. If no taxa are found, an error is raised.
</p>


<h3>Value</h3>

<p>A data frame containing the filtered data with the top N taxa.
</p>

</main>

</div>
</body></html>

