---
format: html
title: fit_hierarchical_clustering()
---

<html><head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes" />
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.15.3/dist/katex.min.css">
<script type="text/javascript">
const macros = { "\\R": "\\textsf{R}", "\\mbox": "\\text", "\\code": "\\texttt"};
function processMathHTML() {
    var l = document.getElementsByClassName('reqn');
    for (let e of l) { katex.render(e.textContent, e, { throwOnError: false, macros }); }
    return;
}</script>
<script defer src="https://cdn.jsdelivr.net/npm/katex@0.15.3/dist/katex.min.js"
    onload="processMathHTML();"></script>
<link rel="stylesheet" type="text/css" href="R.css" />
</head><body><div class="container"><main>

<table style="width: 100%;"><tr><td>fit_hierarchical_clustering</td><td style="text-align: right;">R Documentation</td></tr></table>

<h2>Fit Hierarchical Clustering from a Distance Matrix</h2>

<h3>Description</h3>

<p>Fits a hierarchical clustering model from a precomputed
dissimilarity matrix using 'stats::hclust()'.
</p>


<h3>Usage</h3>

<pre><code class='language-R'>fit_hierarchical_clustering(trait_dissimilarity, clustering_method = "ward.D2")
</code></pre>


<h3>Arguments</h3>

<table role = "presentation">
<tr><td><code id="trait_dissimilarity">trait_dissimilarity</code></td>
<td>
<p>A '&quot;dist&quot;' object (as produced by 'compute_trait_dissimilarity()'
or 'stats::as.dist()'). Must contain no 'NA' or non-finite
values.</p>
</td></tr>
<tr><td><code id="clustering_method">clustering_method</code></td>
<td>
<p>A single character string passed to 'stats::hclust()' as the
'method' argument. Default: '&quot;ward.D2&quot;'. See '?stats::hclust'
for all valid linkage methods.</p>
</td></tr>
</table>


<h3>Value</h3>

<p>An object of class '&quot;hclust&quot;' as returned by 'stats::hclust()'.
</p>


<h3>See Also</h3>

<p>[compute_trait_dissimilarity()],
[assign_functional_type_clusters()]
</p>

</main>

</div>
</body></html>
