# Problematic taxa
tibble::tribble(
  ~sel_name, ~family, ~genus,
  "Cedrus Atlantica", "Pinaceae", "Cedrus",
  "Cedrus Broken)", "Pinaceae", "Cedrus",
  "Cedrus Crumpled)", "Pinaceae", "Cedrus",
  "Cedrus Degraded)", "Pinaceae", "Cedrus",
  "Cedrus Type", "Pinaceae", "Cedrus",
  "Cf Carpinus", "Betulaceae", "Carpinus",
  "Cf Cytisus", "Fabaceae", "Cytisus",
  "Cf Ephedra Fragilis", "Ephedraceae", "Ephedra",
  "Cf Ilex", "Aquifoliaceae", "Ilex",
  "Cf Juniperus", "Cupressaceae", "Juniperus",
  "Cf Larix-Type", "Pinaceae", "Larix",
  "Cf Lonicera", "Caprifoliaceae", "Lonicera",
  "Cf Myrica", "Myricaceae", "Myrica",
  "Cf Myrtus", "Myrtaceae", "Myrtus",
  "Cf Olea", "Oleaceae", "Olea",
  "Cf Platanus", "Platanaceae", "Platanus",
  "Cf Populus Tremula", "Salicaceae", "Populus",
  "Cf Prunus", "Rosaceae", "Prunus",
  "Cf Pterocarya", "Juglandaceae", "Pterocarya",
  "Cf Pterocarya Fraxinifolia", "Juglandaceae", "Pterocarya",
  "Cf Quercus", "Fagaceae", "Quercus",
  "Cf Rhamnaceae", "Rhamnaceae", NA,
  "Cf Rhamnus", "Rhamnaceae", "Rhamnus",
  "Cf Rubus", "Rosaceae", "Rubus",
  "Cf Rubus Chamaemorus", "Rosaceae", "Rubus",
  "Cf Salix Herbacea", "Salicaceae", "Salix",
  "Cf Salix Polaris", "Salicaceae", "Salix",
  "Cf Sambucus", "Adoxaceae", "Sambucus",
  "Cf Sambucus Nigra", "Adoxaceae", "Sambucus",
  "Cf Sambucus Racemosa", "Adoxaceae", "Sambucus",
  "Cf Sorbus", "Rosaceae", "Sorbus",
  "Cf Sorbus Aucuparia", "Rosaceae", "Sorbus",
  "Cf Taxus", "Taxaceae", "Taxus",
  "Cf Viburnum", "Adoxaceae", "Viburnum",
  "Cf Viburnum Opulus", "Adoxaceae", "Viburnum",
  "Cf Viscum", "Santalaceae", "Viscum",
  "Cf Zelkova", "Ulmaceae", "Zelkova",
  "Coniferae Saccate)", NA, NA,
  "Coniferae Type", NA, NA,
  "Coniferae Undiff", NA, NA,
  "Ericales", NA, NA,
  "Ericales Tetrad)", NA, NA,
  "Ericales Undiff", NA, NA,
  "Ericoideae", "Ericaceae", NA,
  "Hedera Helix", "Araliaceae", "Hedera",
  "Hedera Helix-Type", "Araliaceae", "Hedera",
  "Hedera Type", "Araliaceae", "Hedera",
  "Hippocastanoideae", "Sapindaceae", NA,
  "Normapolles", NA, NA,
  "Olea Europaea", "Oleaceae", "Olea",
  "Olea Phillyrea", "Oleaceae", "Phillyrea",
  "Olea Type", "Oleaceae", "Olea",
  "Periploca", "Apocynaceae", "Periploca",
  "Salix Caprea", "Salicaceae", "Salix",
  "Salix Glauca-Type", "Salicaceae", "Salix",
  "Salix Herbacea", "Salicaceae", "Salix",
  "Salix Herbacea-Type", "Salicaceae", "Salix",
  "Salix Pentandra-Type", "Salicaceae", "Salix",
  "Salix Polaris-Type", "Salicaceae", "Salix",
  "Salix Type", "Salicaceae", "Salix",
  "Salix Undiff", "Salicaceae", "Salix",
  "Spermatophyta Undiff(Deciduous Trees)", NA, NA,
  "Spermatophyta Undiff(Shrubs)", NA, NA,
  "Spermatophyta Undiff(Trees)", NA, NA,
  "Spermatophyta Undiff(Trees/Shrubs)", NA, NA,
  "Ulmus Corroded)", "Ulmaceae", "Ulmus",
  "Ulmus Glabra-Type", "Ulmaceae", "Ulmus",
  "Ulmus Minor", "Ulmaceae", "Ulmus",
  "Ulmus Zelkova", "Ulmaceae", "Ulmus",
  "Urticalean Rosids", NA, NA
)
